In [45]:
import numpy as np
np.random.seed(42)
A = np.random.randint(10, size=(3, 4))
B = np.random.randint(10, size=(3, 4))
print(A)
print(B)

[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]]
[[7 2 5 4]
 [1 7 5 1]
 [4 0 9 5]]


In [46]:
np.vstack([A, B])

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7],
       [7, 2, 5, 4],
       [1, 7, 5, 1],
       [4, 0, 9, 5]])

In [47]:
np.hstack([A, B])

array([[6, 3, 7, 4, 7, 2, 5, 4],
       [6, 9, 2, 6, 1, 7, 5, 1],
       [7, 4, 3, 7, 4, 0, 9, 5]])

In [48]:
print(np.intersect1d(A, B)) 

[2 4 7 9]


In [49]:
indices = np.where((A >= 5)&(A <= 8))
print(A[indices])

[6 7 6 6 7 7]


In [17]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
solution = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[solution]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [51]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

output = []
for group_val in np.unique(grouping_column):
    output.append([group_val, numeric_column[grouping_column==group_val].mean()])

output

[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [52]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
MMT = df.loc[: , "Manufacturer":"Type"]
MMT2 = MMT.iloc[::20]
MMT2.head(10)

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [53]:
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean()) 
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean()) 
df.head(10)

Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura     Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN      Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi          90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi         100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW        535i  Midsize  17.118605   30.0  21.459091      22.0   
5        Buick     Century  Midsize  14.200000   15.7  17.300000      22.0   
6        Buick     LeSabre    Large  19.900000   20.8  21.459091      19.0   
7        Buick  Roadmaster    Large  22.600000   23.7  24.900000      16.0   
8        Buick     Riviera  Midsize  26.300000   26.3  26.300000      19.0   
9     Cadillac     DeVille    Large  33.000000   34.7  36.300000      16.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   
5         31.0         Driver only        NaN  ...        6.0   189.0   
6         28.0         Driver only      Front  ...        6.0   200.0   
7         25.0         Driver only       Rear  ...        6.0   216.0   
8         27.0         Driver only      Front  ...        5.0   198.0   
9         25.0         Driver only      Front  ...        6.0   206.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   
5      105.0   69.0         41.0           28.0          16.0     NaN   
6      111.0   74.0         42.0           30.5          17.0  3470.0   
7      116.0   78.0         45.0           30.5          21.0  4105.0   
8      108.0    NaN         41.0           26.5          14.0  3495.0   
9      114.0   73.0         43.0           35.0          18.0  3620.0   

    Origin              Make  
0  non-USA     Acura Integra  
1  non-USA      Acura Legend  
2  non-USA           Audi 90  
3  non-USA          Audi 100  
4  non-USA          BMW 535i  
5      USA     Buick Century  
6      USA     Buick LeSabre  
7      USA  Buick Roadmaster  
8      USA     Buick Riviera  
9      USA  Cadillac DeVille  

[10 rows x 27 columns]

In [54]:
df1 = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df1[df1.sum(axis=1) > 100]

0   1   2   3
0  38  21  34  26
1  36  36  19  37
2  37  25  24  39
3  39  24  39  28
4  21  32  29  34
7  13  34  37  23
8  27  35  18  35
9  30  11  29  37